version: '3'
services:
    infant-frontend:
        build: ./
        command: yarn dev
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules