exports.seed = function(knex, Promise) {
    // Deletes ALL existing entries
    return knex('answers').then(function() {
        // Inserts seed entries
        return knex('answers').insert([
            {
                question_guid: 'zenAFirh9j',
                answer: '2 months',
                is_correct: false,
                guid: 'YjpXeiyAoH',
            },
            {
                question_guid: 'zenAFirh9j',
                answer: '4 months',
                is_correct: false,
                guid: '8PwxxuZra5',
            },
            {
                question_guid: 'zenAFirh9j',
                answer: '6 months',
                is_correct: true,
                guid: 'ilUTAj53YX',
            },
            {
                question_guid: 'zenAFirh9j',
                answer: '8 months',
                is_correct: false,
                guid: 'EWmr668vNc',
            },
            {
                question_guid: 'zenAFirh9j',
                answer: '10 months',
                is_correct: false,
                guid: 'xXB3ezFyLn',
            },
            {
                question_guid: '1oCueapMWR',
                answer: 'Vitamin A',
                is_correct: false,
                guid: 'xpUOUGnKZR',
            },
            {
                question_guid: '1oCueapMWR',
                answer: 'Vitamin C',
                is_correct: false,
                guid: 'J97UrA_ZL4',
            },
             {
                question_guid: '1oCueapMWR',
                answer: 'Iron',
                is_correct: true,
                guid: 'WKcyoa_V74',
            },
             {
                question_guid: '1oCueapMWR',
                answer: 'Vitamin D',
                is_correct: false,
                guid: 'Xk7ANUGbsZ',
            },
             {
                question_guid: '1oCueapMWR',
                answer: 'Zinc',
                is_correct: false,
                guid: 'O4NnCYGoVE',
            },
            {
                question_guid: 'uRpdprH5HI',
                answer: '4 months',
                is_correct: false,
                guid: 'GsIxhHoH9p',
            },
            {
                question_guid: 'uRpdprH5HI',
                answer: '6 months',
                is_correct: false,
                guid: 'PZ4e_zT7wb',
            },
            {
                question_guid: 'uRpdprH5HI',
                answer: '8 months',
                is_correct: false,
                guid: 'qSdGIYwINX',
            },
            {
                question_guid: 'uRpdprH5HI',
                answer: '10 months',
                is_correct: false,
                guid: 'dZH89IfhLH',
            },
            {
                question_guid: 'uRpdprH5HI',
                answer: '12 months',
                is_correct: true,
                guid: '_9iYyjNrx4',
            },
            {
                question_guid: '3iwNn6ETQo',
                answer: '1-2 tries',
                is_correct: false,
                guid: 'VjgsGPKYGi',
            },
            {
                question_guid: '3iwNn6ETQo',
                answer: '3-4 tries',
                is_correct: false,
                guid: 'MjyKv168Hw',
            },
            {
                question_guid: '3iwNn6ETQo',
                answer: '5-6 tries',
                is_correct: false,
                guid: 'N~Tk~4PHiE',
            },
            {
                question_guid: '3iwNn6ETQo',
                answer: '7-9 tries',
                is_correct: false,
                guid: 'pMW5Fmmx6O',
            },
            {
                question_guid: '3iwNn6ETQo',
                answer: '10 or more tries',
                is_correct: true,
                guid: 'Jc02j~j6kK',
            },
            {
                question_guid: 'oR7HsRu2xZ',
                answer: 'Vegetables',
                is_correct: false,
                guid: 'as_kdgxgZl',
            },
            {
                question_guid: 'oR7HsRu2xZ',
                answer: 'Fruit',
                is_correct: false,
                guid: 'hMm_ekkst~',
            },
            {
                question_guid: 'oR7HsRu2xZ',
                answer: 'Food with sugar and salt',
                is_correct: false,
                guid: 'wg16_hw8WN',
            },
            {
                question_guid: 'oR7HsRu2xZ',
                answer: 'Bread',
                is_correct: false,
                guid: 'PeZDdoW8uF',
            },
            {
                question_guid: 'oR7HsRu2xZ',
                answer: 'The order doesn\'t matter as long as it is a healthy choice',
                is_correct: true,
                guid: 'OKnimlsoSm',
            },
            {
                question_guid: '8Iutx~rl4s',
                answer: 'provide the right nutrients a baby needs',
                is_correct: false,
                guid: 'XoJvz6SHHZ',
            },
            {
                question_guid: '8Iutx~rl4s',
                answer: 'spoil a baby if done longer than 6 months',
                is_correct: true,
                guid: 'Wy~yzoxFWM',
            },
            {
                question_guid: '8Iutx~rl4s',
                answer: 'protect a baby from illness ',
                is_correct: false,
                guid: 'm5JLpz_kUD',
            },
            {
                question_guid: '8Iutx~rl4s',
                answer: 'help build a connection between mother and baby',
                is_correct: false,
                guid: 'iClvWnDZhy',
            },
            {
                question_guid: '8Iutx~rl4s',
                answer: 'rot a baby’s teeth',
                is_correct: false,
                guid: '4qf8NBEIFO',
            },
            {
                question_guid: 'kPd8h6Qk9k',
                answer: 'Sit up, with or without support',
                is_correct: false,
                guid: 'LM7wjNcm98',
            },
            {
                question_guid: 'kPd8h6Qk9k',
                answer: 'Open their mouth and close their lips around a spoon ',
                is_correct: false,
                guid: 'TBKyC5Pc3K',
            },
            {
                question_guid: 'kPd8h6Qk9k',
                answer: 'Hold their head steady',
                is_correct: false,
                guid: '6sjF~Iuxce',
            },
            {
                question_guid: 'kPd8h6Qk9k',
                answer: 'Do ANY of the above',
                is_correct: false,
                guid: 'Vp_Z~idedW',
            },
            {
                question_guid: 'kPd8h6Qk9k',
                answer: 'Do ALL of the above',
                is_correct: true,
                guid: 'JElNOM2W5Y',
            },
            {
                question_guid: 'jiwFlAGHKs',
                answer: 'Singing a song or using the same words (“Let’s Eat”) right before mealtime',
                is_correct: true,
                guid: '2rR6EbpFgx',
            },
            {
                question_guid: 'jiwFlAGHKs',
                answer: 'Eating at the same time every day',
                is_correct: false,
                guid: 'uA2rhPuyqF',
            },
            {
                question_guid: 'jiwFlAGHKs',
                answer: 'Eating the same food for each meal',
                is_correct: false,
                guid: 'ifaaMpFd8Z',
            },
            {
                question_guid: 'jiwFlAGHKs',
                answer: 'All of the above ',
                is_correct: false,
                guid: 'Q~wEPmeTyb',
            },
            {
                question_guid: 'gdZHYec4pd',
                answer: 'Opening mouth wide ',
                is_correct: false,
                guid: 'jyth~zOTPe',
            },
            {
                question_guid: 'gdZHYec4pd',
                answer: 'Crying or becoming fussy',
                is_correct: false,
                guid: 'Z3E1ZFJSiw',
            },
            {
                question_guid: 'gdZHYec4pd',
                answer: 'Falling asleep',
                is_correct: true,
                guid: 'dhcOVU542J',
            },
            {
                question_guid: 'gdZHYec4pd',
                answer: 'Showing signs of excitement when food/spoon is presented',
                is_correct: false,
                guid: 'Kc7tmg6ez3',
            },
            {
                question_guid: 'gdZHYec4pd',
                answer: 'Putting fingers and hands inside mouth',
                is_correct: false,
                guid: 'o8SoiPZCHX',
            },
            {
                question_guid: 'k9ZzwxZczj',
                answer: 'Stop one feeding at a time',
                is_correct: false,
                guid: 'GL~eEF5Ov_',
            },
            {
                question_guid: 'k9ZzwxZczj',
                answer: 'Wait 3-5 days in between dropping another feeding',
                is_correct: false,
                guid: 'a5DtI3hHXr',
            },
            {
                question_guid: 'k9ZzwxZczj',
                answer: 'Start by dropping mid-day feedings',
                is_correct: false,
                guid: '2~3TQRO1TX',
            },
            {
                question_guid: 'k9ZzwxZczj',
                answer: 'Replace breast milk with formula (<12 months) or fluid cow’s milk (12 months or older)',
                is_correct: false,
                guid: 'qqhZbfDpaK',
            },
            {
                question_guid: 'k9ZzwxZczj',
                answer: 'All of the above',
                is_correct: true,
                guid: 'F7RP0PsqGB',
            },
            {
                question_guid: 'xQ~DQShGjV',
                answer: 'True',
                is_correct: true,
                guid: 'GQy80QqMp2',
            },
            {
                question_guid: 'xQ~DQShGjV',
                answer: 'False',
                is_correct: false,
                guid: '6T8zOehoND',
            },
            {
                question_guid: 'nWzeR9XUyN',
                answer: 'True',
                is_correct: false,
                guid: 'gLLhDCcYqr',
            },
            {
                question_guid: 'nWzeR9XUyN',
                answer: 'False',
                is_correct: true,
                guid: 'Y2MvIHVMXA',
            },
            {
                question_guid: 'AeJ3u5gZLW',
                answer: 'True',
                is_correct: false,
                guid: 'Sr0w58YT5Y',
            },
            {
                question_guid: 'AeJ3u5gZLW',
                answer: 'False',
                is_correct: true,
                guid: 'Uolp3IQW1U',
            },
            {
                question_guid: '3X7XoiXEv1',
                answer: 'True',
                is_correct: true,
                guid: '3Vr2YWDG4f',
            },
            {
                question_guid: '3X7XoiXEv1',
                answer: 'False',
                is_correct: false,
                guid: 'RfCUXq9j4V',
            },
            {
                question_guid: 'wACXrOri9z',
                answer: 'True',
                is_correct: true,
                guid: 'GsPD4bsFjU',
            },
            {
                question_guid: 'wACXrOri9z',
                answer: 'False',
                is_correct: false,
                guid: 'KqdFTXRG1T',
            },
            {
                question_guid: 'J3Mioq_z2_',
                answer: 'True',
                is_correct: false,
                guid: 'UkosMG_xT9',
            },
            {
                question_guid: 'J3Mioq_z2_',
                answer: 'False',
                is_correct: true,
                guid: 'zi4RNo11L~',
            },
            {
                question_guid: 'brlrwuZ2tk',
                answer: 'True',
                is_correct: false,
                guid: 'jprast~3Yj',
            },
            {
                question_guid: 'brlrwuZ2tk',
                answer: 'False',
                is_correct: true,
                guid: 'oaeNDsLNbx',
            },
            {
                question_guid: 'NNb04IUDEm',
                answer: 'True',
                is_correct: true,
                guid: 'GMLPucuITh',
            },
            {
                question_guid: 'NNb04IUDEm',
                answer: 'False',
                is_correct: false,
                guid: 'xwNE3xSNvn',
            },
            {
                question_guid: '~Wti7H~ltF',
                answer: 'True',
                is_correct: true,
                guid: 'tgXHRpevkv',
            },
            {
                question_guid: '~Wti7H~ltF',
                answer: 'False',
                is_correct: false,
                guid: 'MXFNNHjcpn',
            },
            {
                question_guid: 'pR2n53RWJe',
                answer: 'True',
                is_correct: true,
                guid: '0PZOICFmDc',
            },
            {
                question_guid: 'pR2n53RWJe',
                answer: 'False',
                is_correct: false,
                guid: 'eQyIeVBlKT',
            },






        ]);
    });
};
